In [1]:
import pyspark 
from pyspark.sql import SparkSession,Row,DataFrame
import pyspark.sql.functions as F
from pyspark.sql.types import *
from delta import *


spark=SparkSession.builder\
        .appName("configDB")\
        .config("spark.sql.warehouse.dir", "/Users/eduardoalberto/LoadFile/repository/metastore/") \
        .config("spark.sql.shuffle.partitions","8")\
        .enableHiveSupport()\
        .getOrCreate()
sc = spark.sparkContext
spark.sparkContext.setLogLevel("OFF") 
print('PySpark Version :'+spark.version)
print('PySpark Version :'+spark.sparkContext.version)

spark

25/03/13 22:00:02 WARN Utils: Your hostname, MacBook-Pro-de-Eduardo.local resolves to a loopback address: 127.0.0.1; using 192.168.3.180 instead (on interface en0)
25/03/13 22:00:02 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/03/13 22:00:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
25/03/13 22:00:03 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

PySpark Version :3.5.4
PySpark Version :3.5.4

In [4]:
spark.sql("""
    CREATE DATABASE IF NOT EXISTS dev150
    LOCATION '/Users/eduardoalberto/LoadFile/repository/database'
""")

DataFrame[]

In [5]:
spark.sql("""
    CREATE TABLE IF NOT EXISTS dev150.tb_ratingmovie
    USING PARQUET
    LOCATION '/Users/eduardoalberto/LoadFile/repository/deltaTable/tb_ratingmovie/dt_ref_carga=2025-03-11'
""")

DataFrame[]

In [6]:
spark.table("dev150.tb_ratingmovie").toPandas()

,name,imdb_id,overview,revenue,runtime,status,title,vote_average,vote_count,popularity,name_geners,total
0,None,tt0119116,"In 2257, a taxi driver is unintentionally give...",263920180,126.0,Released,The Fifth Element,7,3962,24.305260,Drama,11966
1,None,tt0078788,"At the height of the Vietnam war, Captain Benj...",89460381,153.0,Released,Apocalypse Now,8,2112,13.596300,Action,4489
2,Before... Collection,tt0381681,Nine years ago two strangers met by chance and...,15992615,80.0,Released,Before Sunset,7,734,7.048957,Crime,1682
3,Heart of Gold Collection,tt0168629,"Selma, a Czech immigrant on the verge of blind...",40031879,140.0,Released,Dancer in the Dark,7,392,10.684806,Animation,1124
4,Deuce Bigalow Collection,tt0205000,"Deuce Bigalow is a less than attractive, down ...",65535067,88.0,Released,Deuce Bigalow: Male Gigolo,5,314,6.567794,Music,487
5,None,tt0185125,A single mother in Madrid sees her only son di...,67872296,101.0,Released,All About My Mother,7,337,10.000915,Documentary,3415
6,None,tt0169547,"Lester Burnham, a depressed suburban father in...",356296601,122.0,Released,American Beauty,7,3438,20.726578,Fantasy,704
7,Finding Nemo Collection,tt0266543,"Nemo, an adventurous young clownfish, is unexp...",940335536,100.0,Released,Finding Nemo,7,6292,25.497794,Adventure,1514
8,In China They Eat Dogs Collection,tt0246692,"The last wish of the dying ""Monk"" is for his f...",0,95.0,Released,Old Men in New Cars: In China They Eat Dogs II,6,37,4.003761,Family,524
9,None,tt0268437,A lawyer becomes a fisherman from frustration....,0,97.0,Released,The Man Who Sued God,6,23,1.741405,Mystery,554
10,None,tt0411705,"Matt, a young glaciologist, soars across the v...",1574623,66.0,Released,9 Songs,5,103,18.847707,Horror,2618
11,The Sheriff and the Satellite Kid Collection,tt0079859,A young humanoid alien who gets stranded on ea...,0,88.0,Released,The Sheriff and the Satellite Kid,5,69,3.812074,TV Movie,390
12,None,tt0462538,After Homer accidentally pollutes the town's w...,527068851,87.0,Released,The Simpsons Movie,6,2335,14.302911,Comedy,8817
13,None,tt0036818,Die Feuerzangenbowle from Director Helmut Weis...,0,97.0,Released,The Punch Bowl,6,41,2.098595,Science Fiction,646
14,None,tt0329632,The film starts in the early evening of a norm...,0,107.0,Released,Sophiiiie!,6,1,0.216899,Romance,1191